### ISSUE TITLE
Could not open DBus in manager thread

### ISSUE THREAD

**Issue by ctrysbita** [ardera/omxplayer_video_player#5]
[omxplayer_video_player plugin] Could not open DBus in manager thread. sd_bus_open_user: No such file or directory

Using Flutter 2.0.2 under debug mode.
The video is the example in video_player plugin https://www.sample-videos.com/video123/mp4/720/big_buck_bunny_720p_20mb.mp4

**Comment by ctrysbita** [comment]
Fixed.
The session dbus does not start on login by default if you are using pi without desktop.
```bash
export $(dbus-launch)
flutter-pi flutter_assets
```

**Comment by ardera** [comment]
Yeah exactly, should probably mention this in the readme.
