### ISSUE TITLE
how to use it flutter desktop application?

### ISSUE THREAD

**Issue by kanakapalli** [ardera/omxplayer_video_player#6]
how to use it in flutter desktop applications.
I'm trying to implement a video player in the flutter desktop application.

**Comment by ardera** [comment]
Sorry, this only works in combination with [flutter-pi](https://github.com/ardera/flutter-pi) and it's not possible to get it working on desktop platforms. On desktop platforms, flutter doesn't have enough control to interleave omxplayer with the flutter contents, i.e. to get some UI to be drawn below and some above the video displayed by omxplayer.

There are a lot of other video player implementations for desktop you can use though.

**Comment by Kovalik98** [comment]
Hi @ardera ! could you provide any examples of video player implementation for desktops. I have been looking for a solution to the problem for a long time but I can't find it

**Comment by ardera** [comment]
Wow, you're right, there aren't any video player implementations for desktop. I've seen `vlc_video_player` recently and I thought that was for desktop but it's not

**Comment by asingh1098** [comment]
Since your plugin does not support desktop platforms. It's my humble request to remove the desktop platform tags from the [pub dev](https://pub.dev/packages/omxplayer_video_player) so that other people don't get confused as I also thought that your plugin works for the desktop platform as well but it doesn't.

**Comment by ardera** [comment]
> Since your plugin does not support desktop platforms. It's my humble request to remove the desktop platform tags from the [pub dev](https://pub.dev/packages/omxplayer_video_player) so that other people don't get confused as I also thought that your plugin works for the desktop platform as well but it doesn't.

I agree that's confusing but that's not my decision I'm afraid. I didn't tell pub.dev to list those platforms as supported and I also don't even know if it's possible to remove them. Maybe it thinks it's cross-platform because it contains no native code? I'll add a hint in the readme.
