### ISSUE TITLE
Not working on Pi Zero 2

### ISSUE THREAD

**Issue by onix-mensakas** [ardera/omxplayer_video_player#8]
I haven't been able to playback any video in a Pi Zero 2 (did not test in other targets).

**Platform**: Raspberry Pi Zero 2 (BCM2835)
**OS**: Raspbian GNU/Linux 10 (buster)
**Arch**: armv7l

After importing and successfully checking for platform side and using this plugin's implementation, when I try to play a video back through a regular VideoPlayer plugin and using either file and network based VideoPlayerController instances, it doesn't display in the app, and executable logs following errors to console:

`[omxplayer_video_player plugin] Could not read DBus property: org.freedesktop.DBus.Error.NoReply, Message recipient disconnected from message bus without replying`
`[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(dbus-error, org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying, null, null)`
`#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)`
`#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)`
`<asynchronous suspension>`
`#2      VideoPlayerController.initialize (package:video_player/video_player.dart:351:19)`
`<asynchronous suspension>`

I have omxplayer installed locally. Am I missing something?

**Comment by ardera** [comment]
Looks like omxplayer crashed, I'm afraid there's not a lot you can do about that.

You can try using the newer gstreamer player in flutter-pi's [`feature/gstreamer-video-player`](https://github.com/ardera/flutter-pi/tree/feature/gstreamer-video-player) branch. (Don't need to install any pub packages for that)

**Comment by onix-mensakas** [comment]
That's weird, I just tried running omxplayer manually from the terminal while app was running, and seems it's actually playing the file with no problems, it overlays the video over the Flutter app, and after I close omxplayer, app is shown again.

I will be trying this other solution, thanks for the fast reply!

**Comment by onix-mensakas** [comment]
It is working with both flutter-pi branches now, I think somehow I was messing badly with a VideoPlayerController.

I can confirm that  [`master`] (with omxplayer) works more fluidly in the Pi Zero 2: I tried [`feature/gstreamer-video-player`] and sometimes frames drop randomly, and almost all the times on recompositions/user interactions it drops frames too. I will be sticking with [`master`] by now.

Thanks for the great work!

**Comment by ardera** [comment]
> sometimes frames drop randomly, and almost all the times on recompositions/user interactions it drops frames too.

I see, yeah right now the gstreamer players framerate is coupled to the flutter framerate, it's using a simple OpenGL texture as the video view. So if flutter drops a frame the video will drop a frame too. It's possible to decouple them, which is what omxplayer is doing by default, that's why it's not a problem there. That's a thing I can implement in the future.
